node(label: 'builder'){
    
    cleanWs()
    checkout scm

    properties([parameters([
        string(name: 'APP_NAME', description: 'APP'),
        string(name: 'ENVIRONMENT', description: 'DEV')
    ])])

    def fullCfg = readYaml file: 'General_CD/config.yml'
    def cfg = [:]

    def configFound = false
    try {
        cfg = fullCfg.apps[params.APP_NAME][ENVIRONMENT.toLowerCase()]
        configFound = true
    } catch(Exception e){
        echo "Config not found"
    }

    // def appNames = []
    // fullCfg.apps.each { k, v ->
    //     if (v.contains(ENVIRONMENT.toLowerCase())){
    //         appNames << k
    //     }
    // }

    stage('init'){
        println(ENVIRONMENT)
        println(cfg.k8s.namespace)
        println(cfg.k8s.url)

        currentBuild.displayName = "${env.BUILD_NUMBER} ${APP_NAME} ${cfg.k8s.namespace}"
    }
}